# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "release" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        experimental: [false]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install current package
      run: |
        python -m pip install -e .
    - name: Test with pytest
      run: |
        pytest --config-file pytest.server.ini
